export const lightTheme = {
  bgSectionContainer: '#F7FAFC',
  bgAccordionContainer: '#EDF2F7',
  bgItem: '#fff',
  bgButtonCustomsActive: '#FBEBEB',
  bgButtonCustomsDisabled: '#fff',
  bgButtonTheme: '#A0AEC0',
  bgNumberPage: '#1A202C',
  colorPrimary: '#1A202C',
  colorSecondary: '#4A5568',
  colorNumberPage: '#fff',
  colorButtonTheme: '#000',
  colorButtonCustomsActive: '#D95757',
  colorButtonCustomsDisabled: '#1A202C',
  borderButtonCustoms: '#fff',
  borderButtonCustomsActive: '#D95757',
  borderButtonTheme: '#EDF2F7',
}

export const darkTheme = {
  bgSectionContainer: '#4A5568',
  bgAccordionContainer: '#2D3748',
  bgItem: '#1A202C',
  bgButtonCustomsActive: '#D95757',
  bgButtonCustomsDisabled: '#D95757',
  bgButtonTheme: '#1A202C',
  bgNumberPage: '#fff',
  colorPrimary: '#fff',
  colorSecondary: '#F7FAFC',
  colorNumberPage: '#1A202C',
  colorButtonTheme: '#fff',
  colorButtonCustomsActive: '#fff',
  colorButtonCustomsDisabled: '#fff',
  borderButtonCustomsActive: '#4B0F00',
  borderButtonCustoms: '#4B0F00',
  borderButtonTheme: '#fff',
}
